# Generated by Django 5.1.1 on 2026-08-19 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("tasks_created", models.PositiveIntegerField(default=0)),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("notes_created", models.PositiveIntegerField(default=0)),
                ("events_scheduled", models.PositiveIntegerField(default=0)),
                ("current_streak_days", models.PositiveIntegerField(default=0)),
                ("longest_streak_days", models.PositiveIntegerField(default=0)),
                ("ai_summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "progress report",
                "verbose_name_plural": "progress reports",
                "db_table": "analytics_progress_report",
                "ordering": ["-period_end"],
                "indexes": [
                    models.Index(
                        fields=["user", "period_end"],
                        name="analytics_p_user_id_1f360f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "period_start", "period_end"),
                        name="unique_progress_report_period_per_user",
                    )
                ],
            },
        ),
    ]
