# Generated by Django 5.1.1 on 2026-08-18 05:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'family',
                'verbose_name_plural': 'families',
                'db_table': 'family_family',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_contacts_added', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='family.family')),
            ],
            options={
                'verbose_name': 'emergency contact',
                'verbose_name_plural': 'emergency contacts',
                'db_table': 'family_emergency_contact',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['family', 'is_active'], name='family_emer_family__8e3ce9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='family.family')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_family_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'family invitation',
                'verbose_name_plural': 'family invitations',
                'db_table': 'family_invitation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['family', 'status'], name='family_invi_family__64a204_idx'), models.Index(fields=['invited_email', 'status'], name='family_invi_invited_8b1494_idx')],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='family.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'family membership',
                'verbose_name_plural': 'family memberships',
                'db_table': 'family_membership',
                'ordering': ['role', 'created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='family_memb_user_id_5086c2_idx'), models.Index(fields=['family', 'is_active'], name='family_memb_family__59a2c2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('family', 'user'), name='unique_active_membership_per_family_user')],
            },
        ),
        migrations.CreateModel(
            name='SharedResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('task', 'Task'), ('event', 'Event'), ('note', 'Note')], max_length=10)),
                ('resource_id', models.UUIDField()),
                ('can_edit', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_resources', to='family.family')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_resources_owned', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_resources_shared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shared resource',
                'verbose_name_plural': 'shared resources',
                'db_table': 'family_shared_resource',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['family', 'resource_type', 'is_active'], name='family_shar_family__b26971_idx'), models.Index(fields=['owner', 'resource_type'], name='family_shar_owner_i_92e07b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('family', 'resource_type', 'resource_id'), name='unique_active_share_per_family_resource')],
            },
        ),
    ]
