# Generated by Django 5.1.1 on 2026-08-16 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_companion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="memoryfact",
            name="unique_memory_fact_per_user",
        ),
        migrations.RemoveIndex(
            model_name="memoryfact",
            name="ai_companio_user_id_95ed8a_idx",
        ),
        migrations.AddField(
            model_name="memoryfact",
            name="category",
            field=models.CharField(
                choices=[
                    ("preference", "Preference"),
                    ("important_date", "Important date"),
                    ("routine", "Routine"),
                    ("relationship", "Relationship"),
                    ("personal_fact", "Personal fact"),
                ],
                default="personal_fact",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="memoryfact",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memoryfact",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="memoryfact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="memoryfact",
            index=models.Index(
                fields=["user", "is_active", "created_at"],
                name="ai_companio_user_id_b50d66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memoryfact",
            index=models.Index(
                fields=["user", "category"], name="ai_companio_user_id_ff9f51_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryfact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "fact_text"),
                name="unique_active_memory_fact_per_user",
            ),
        ),
    ]
